FROM ubuntu

RUN apt-get update
RUN apt-get install nginx -y

CMD ["echo","Hello World"]

#copying files content and default.conf the destinations
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./content content

#attaching dir content as a volume
VOLUME ["/content"]

ARG IS_READY

#generates two different index.html for two cases of IS_REAADY arg
RUN if["$IS_READY"= "true"]; then echo "We are ready"> /content/index.html ; else echo "We are not ready"> /content/index.html; fi

EXPOSE 8080

CMD ["nginx","-g","daemon off;"]